### ISSUE TITLE
Stop using FastAPI

### ISSUE THREAD

**Issue by binyamin555** [xpodev/ez-web#46]
Currently, `FastAPI` is one of the dependencies of EZ Web. However, the value it gives to the project in terms of features doesn't compare to how much it makes the framework more unnecessarily complex.

Instead, we can move to use `starlette` alone  and implement any desired functionality ourselves.

Starlette already handles routing and the basic interaction with the web server.

What we'll need to implement ourselves:
* Automatic request parsing (via `pydantic`)
* Dependency injection
* Automatic response type

Implementing those shouldn't be too hard and will allow us to modify them to our needs.

**Comment by neriyaco** [comment]
I'm pretty sure we can close this issue, we don't use `FastAPI` anymore.

**Comment by binyamin555** [comment]
We haven't fully implemented the above features.

Although, we might end up not implementing them till a later version.
